# Site
repository: tanmayeemandala/resume
favicon: images/favicon.ico

# Personal info
name: Tanmayee Mandala
title: Data Analyst
email: tanmayee.mandala1@gmail.com
website: www.github.com/tanmayee_mandala/resume

# Social links
#twitter_username: facespics
github_username:  tanmayeemandala
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: tmandal1
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
#about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. I am a results-driven, solutions-oriented and insightful industrial and systems engineer who is passionate with extensive experience in data analysis, data mining, quality, reliability, continuous process improvement, lean six sigma and operations management. Enthusiastic team player with well-developed troubleshooting and analytical abilities. Skilled in performing root-cause analysis, conceptualizing, data visualization, developing and implementing solutions for better quality outcomes, resources optimization, and waste reduction. Good understanding of Quality system standards ISO 9001.

  Excellent interpersonal, communication and presentation skills. Highly motivated leader and professional, detail-oriented and proficient at building and maintaining professional relationships. Experienced in fast-paced environments while performing with a positive attitude and diligent approach towards personal and professional growth and yield. Have a strong predilection for turning data into information, information into insight and insight into business decisions.

Core Competencies:
• Lean & Six Sigma
• Operations management
• Data analytics & visualization
• Continuous process improvement
• Quality and Reliability
• Business Intelligence
• Data Analyst
• Business Data Analyst

Technical Skills:
• Languages: Python
• Statistical Tools: R, Minitab, SAS
• Database: MS SQL
• Optimization Tool: AMPL
• Visualization Tools: Tableau, Microsoft Power BI
• Tools: Simio, AutoCAD, Microsoft Office
  
#I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
